# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from watchtower.peer.proto import watchtower_pb2 as watchtower__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in watchtower_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WatchtowerPeerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/watchtower.WatchtowerPeer/Heartbeat',
                request_serializer=watchtower__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=watchtower__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.ShareEvent = channel.unary_unary(
                '/watchtower.WatchtowerPeer/ShareEvent',
                request_serializer=watchtower__pb2.EventShareRequest.SerializeToString,
                response_deserializer=watchtower__pb2.EventShareResponse.FromString,
                _registered_method=True)
        self.ShareTopology = channel.unary_unary(
                '/watchtower.WatchtowerPeer/ShareTopology',
                request_serializer=watchtower__pb2.TopologyFragmentRequest.SerializeToString,
                response_deserializer=watchtower__pb2.TopologyFragmentResponse.FromString,
                _registered_method=True)
        self.ShareFinding = channel.unary_unary(
                '/watchtower.WatchtowerPeer/ShareFinding',
                request_serializer=watchtower__pb2.FindingShareRequest.SerializeToString,
                response_deserializer=watchtower__pb2.FindingShareResponse.FromString,
                _registered_method=True)


class WatchtowerPeerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Heartbeat(self, request, context):
        """Bidirectional heartbeat -- each side learns the other's status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareEvent(self, request, context):
        """Push a local event to a direct peer (1-hop only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareTopology(self, request, context):
        """Push a topology fragment (periodic)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareFinding(self, request, context):
        """Push a finding with TTL-limited gossip
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WatchtowerPeerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=watchtower__pb2.HeartbeatRequest.FromString,
                    response_serializer=watchtower__pb2.HeartbeatResponse.SerializeToString,
            ),
            'ShareEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareEvent,
                    request_deserializer=watchtower__pb2.EventShareRequest.FromString,
                    response_serializer=watchtower__pb2.EventShareResponse.SerializeToString,
            ),
            'ShareTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareTopology,
                    request_deserializer=watchtower__pb2.TopologyFragmentRequest.FromString,
                    response_serializer=watchtower__pb2.TopologyFragmentResponse.SerializeToString,
            ),
            'ShareFinding': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareFinding,
                    request_deserializer=watchtower__pb2.FindingShareRequest.FromString,
                    response_serializer=watchtower__pb2.FindingShareResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'watchtower.WatchtowerPeer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('watchtower.WatchtowerPeer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WatchtowerPeer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/watchtower.WatchtowerPeer/Heartbeat',
            watchtower__pb2.HeartbeatRequest.SerializeToString,
            watchtower__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/watchtower.WatchtowerPeer/ShareEvent',
            watchtower__pb2.EventShareRequest.SerializeToString,
            watchtower__pb2.EventShareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/watchtower.WatchtowerPeer/ShareTopology',
            watchtower__pb2.TopologyFragmentRequest.SerializeToString,
            watchtower__pb2.TopologyFragmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareFinding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/watchtower.WatchtowerPeer/ShareFinding',
            watchtower__pb2.FindingShareRequest.SerializeToString,
            watchtower__pb2.FindingShareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
